### ISSUE TITLE
BOM-ZU2 - Clarification needed

### ISSUE THREAD

**Issue by Deynet88** [FlorentBroise/BRS-Printers-Mod#3]
Hi Florent,

I have two questions:

1) BK10: Needed quantity should be 3 instead of 2, right?
2) BK10: With normal or angular bearings?

![grafik](https://github.com/FlorentBroise/BRS-Printers-Mod/assets/50778696/f67a1111-b212-4afd-a28a-af839f45be9f)

Thanks in advance.

Best regards

**Comment by FlorentBroise** [comment]
Hello Deynet88

1/ Yes 3, I will correct this mistake. 

2/ BK10 with angular bearings is not that easy to find as an SFU package kit, I use to buy angular bearing by myself and swap them in the BK10 housing.
Angular bearing are actually better on the theorical aspect to hold the weight and have a better reliability. That said the stock non angularat bearing behave ok too since it never exceeds their axial load limit...
If you want to be square with the principle, changing to angular bearing is a good thing

**Comment by FlorentBroise** [comment]
I guess the issue has been cleared, I'm closing it ;)
